{{/*
Copyright Simon Li. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.geoipVolume.enabled .Values.geoipUpdate.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "common.names.fullname" . }}-geoip-update
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: geoip-update
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.geoipUpdate.schedule | quote }}
  concurrencyPolicy: {{ .Values.geoipUpdate.concurrencyPolicy | default "Forbid" }}
  {{- if .Values.geoipUpdate.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.geoipUpdate.startingDeadlineSeconds }}
  {{- end }}
  {{- if .Values.geoipUpdate.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.geoipUpdate.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.geoipUpdate.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.geoipUpdate.failedJobsHistoryLimit }}
  {{- end }}
  suspend: {{ .Values.geoipUpdate.suspend | default false }}
  jobTemplate:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: geoip-update
      {{- if .Values.geoipUpdate.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.geoipUpdate.podAnnotations "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.geoipUpdate.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.geoipUpdate.ttlSecondsAfterFinished }}
      {{- end }}
      backoffLimit: {{ .Values.geoipUpdate.backoffLimit | default 3 }}
      template:
        metadata:
          labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 12 }}
            app.kubernetes.io/component: geoip-update
        spec:
          {{- include "powerdns-auth.geoipUpdate.podSpec" . | nindent 10 }}
{{- end }}
