{{- /*
Copyright Simon Li. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if (include "powerdns-auth.createDatabaseSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-auth.databaseSecretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: auth
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  DB_USER: {{ include "powerdns-auth.databaseUsername" . | b64enc }}
  DB_PASSWORD: {{ include "powerdns-auth.databasePassword" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-auth.databaseAdminSecretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: auth
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  DB_USER: {{ include "powerdns-auth.databaseAdminUsername" . | b64enc }}
  DB_PASSWORD: {{ include "powerdns-auth.databaseAdminPassword" . | b64enc }}
{{- end }}
