{{- /*
Copyright Simon Li. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- /*
Secret creation logic:
- GitHub mode with token: create secret with github-token
- GitHub mode without token (public repo): skip secret creation
- MaxMind mode: create secret with account-id and license-key
*/}}

{{- $isGitHubMode := eq .Values.source.type "github" }}
{{- $githubTokenProvided := and $isGitHubMode .Values.source.github.token }}
{{- $maxmindMode := not $isGitHubMode }}
{{- $needSecret := or $githubTokenProvided $maxmindMode }}

{{- if and $needSecret (not .Values.source.existingSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geoip-database.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if $githubTokenProvided }}
  # GitHub relay mode (private repo)
  github-token: {{ .Values.source.github.token | b64enc | quote }}
  {{- else if $maxmindMode }}
  # MaxMind direct mode
  account-id: {{ .Values.source.maxmind.accountId | default "0" | toString | b64enc | quote }}
  license-key: {{ .Values.source.maxmind.licenseKey | default "" | b64enc | quote }}
  {{- if .Values.source.maxmind.proxyUserPassword }}
  proxy-user-password: {{ .Values.source.maxmind.proxyUserPassword | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
