{{- /*
Copyright Anthropic, Inc.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.coordinator.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "citus.coordinator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "citus.coordinator.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.coordinator.pdb.minAvailable }}
  minAvailable: {{ .Values.coordinator.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.coordinator.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.coordinator.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels: {{- include "citus.coordinator.selectorLabels" . | nindent 6 }}
{{- end }}
---
{{- if .Values.worker.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "citus.worker.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "citus.worker.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.worker.pdb.minAvailable }}
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.worker.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.worker.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels: {{- include "citus.worker.selectorLabels" . | nindent 6 }}
{{- end }}
