{{- /*
Copyright Anthropic, Inc.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if (include "citus.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "citus.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "citus.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.postgresPassword }}
  postgres-password: {{ .Values.auth.postgresPassword | b64enc | quote }}
  {{- else }}
  postgres-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.password }}
  password: {{ .Values.auth.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}
