{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nacos.fullname" . }}
  namespace: {{ include "nacos.namespace" . }}
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nacos.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow inbound traffic from pods in the same namespace
    - from:
        - podSelector: {}
      ports:
        - port: {{ .Values.service.ports.http }}
          protocol: TCP
        - port: {{ .Values.service.ports.client }}
          protocol: TCP
        - port: {{ .Values.service.ports.clientRpc }}
          protocol: TCP
        - port: {{ .Values.service.ports.raftRpc }}
          protocol: TCP
        - port: {{ .Values.service.ports.mcp }}
          protocol: TCP
        - port: 7848
          protocol: TCP
    {{- if .Values.networkPolicy.allowExternal }}
    # Allow external inbound traffic
    - ports:
        - port: {{ .Values.service.ports.http }}
          protocol: TCP
        - port: {{ .Values.service.ports.client }}
          protocol: TCP
        - port: {{ .Values.service.ports.clientRpc }}
          protocol: TCP
        - port: {{ .Values.service.ports.mcp }}
          protocol: TCP
    {{- end }}
    {{- with .Values.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    # Allow cluster internal communication
    - to:
        - podSelector:
            matchLabels:
              {{- include "nacos.selectorLabels" . | nindent 14 }}
      ports:
        - port: {{ .Values.service.ports.client }}
          protocol: TCP
        - port: {{ .Values.service.ports.clientRpc }}
          protocol: TCP
        - port: {{ .Values.service.ports.raftRpc }}
          protocol: TCP
        - port: 7848
          protocol: TCP
    # Allow database connection
    {{- if include "nacos.database.external" . }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: {{ .Values.database.port }}
          protocol: TCP
    {{- end }}
    {{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
