{{- if and .Values.podDisruptionBudget.enabled (ne .Values.mode "standalone") }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nacos.fullname" . }}
  namespace: {{ include "nacos.namespace" . }}
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  maxUnavailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "nacos.selectorLabels" . | nindent 6 }}
{{- end }}
