{{- /*
Copyright Anthropic. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if include "powerdns-admin.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-admin.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.powerdnsAdmin.secretKey | b64enc | quote }}
  SALT: {{ .Values.powerdnsAdmin.salt | default (randAlphaNum 29 | b64enc) | b64enc | quote }}
{{- end }}
{{- if and (ne .Values.database.type "sqlite") (not .Values.externalDatabase.existingSecret) .Values.externalDatabase.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-admin.database.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
{{- if and .Values.powerdnsApi.enabled (not .Values.powerdnsApi.existingSecret) .Values.powerdnsApi.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-admin.powerdnsApi.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  api-key: {{ .Values.powerdnsApi.key | b64enc | quote }}
{{- end }}
{{- if and .Values.auth.ldap.enabled (not .Values.auth.ldap.existingSecret) .Values.auth.ldap.adminPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-admin.auth.ldap.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  bind-password: {{ .Values.auth.ldap.adminPassword | b64enc | quote }}
{{- end }}
{{- if and .Values.auth.saml.enabled (not .Values.auth.saml.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-admin.auth.saml.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.saml.certData }}
  saml-cert: {{ .Values.auth.saml.certData | quote }}
  {{- end }}
  {{- if .Values.auth.saml.keyData }}
  saml-key: {{ .Values.auth.saml.keyData | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.auth.oidc.enabled (not .Values.auth.oidc.existingSecret) .Values.auth.oidc.clientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-admin.auth.oidc.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  client-secret: {{ .Values.auth.oidc.clientSecret | b64enc | quote }}
{{- end }}
{{- if and .Values.auth.google.enabled (not .Values.auth.google.existingSecret) .Values.auth.google.clientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-admin.auth.google.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  client-secret: {{ .Values.auth.google.clientSecret | b64enc | quote }}
{{- end }}
{{- if and .Values.auth.github.enabled (not .Values.auth.github.existingSecret) .Values.auth.github.clientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-admin.auth.github.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  client-secret: {{ .Values.auth.github.clientSecret | b64enc | quote }}
{{- end }}
{{- if and .Values.auth.azure.enabled (not .Values.auth.azure.existingSecret) .Values.auth.azure.clientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-admin.auth.azure.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  client-secret: {{ .Values.auth.azure.clientSecret | b64enc | quote }}
{{- end }}
{{- if and .Values.mail.enabled (not .Values.mail.existingSecret) .Values.mail.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-admin.mail.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  smtp-password: {{ .Values.mail.password | b64enc | quote }}
{{- end }}
