{{- if and .Values.server.enabled .Values.backup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.names.fullname" . }}-backup
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: backup
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "common.names.fullname" . }}-backup
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: backup
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 12 }}
            app.kubernetes.io/component: backup
        spec:
          serviceAccountName: {{ include "common.names.fullname" . }}-backup
          restartPolicy: OnFailure
          
          ## Init Container: Create snapshot using Vault image
          initContainers:
            - name: snapshot
              image: {{ include "vault.server.image" . }}
              imagePullPolicy: {{ .Values.server.image.pullPolicy }}
              command:
                - /bin/sh
                - -ec
                - |
                  set -e
                  echo "=== Vault Snapshot Job Started ==="
                  echo "Time: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
                  echo "Cluster: {{ .Values.backup.clusterName | default (include "common.names.fullname" .) }}"
                  
                  VAULT_ADDR="http://{{ include "common.names.fullname" . }}-active:{{ .Values.server.service.general.ports.http }}"
                  export VAULT_ADDR
                  
                  # Wait for Vault to be ready
                  echo "Waiting for Vault to be ready..."
                  for i in $(seq 1 60); do
                    if vault status 2>&1 | grep -q "Sealed.*false"; then
                      echo "Vault is unsealed and ready"
                      break
                    fi
                    if [ $i -eq 60 ]; then
                      echo "ERROR: Timeout waiting for Vault"
                      exit 1
                    fi
                    echo "Waiting... ($i/60)"
                    sleep 5
                  done
                  
                  {{- if .Values.backup.vaultTokenSecretName }}
                  # Use provided token
                  export VAULT_TOKEN=$(cat /vault/token/{{ .Values.backup.vaultTokenSecretKey }})
                  {{- else }}
                  # Authenticate with Kubernetes
                  echo "Authenticating with Kubernetes..."
                  JWT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
                  VAULT_TOKEN=$(vault write -field=token auth/kubernetes/login role=backup jwt=$JWT 2>/dev/null || echo "")
                  
                  if [ -z "$VAULT_TOKEN" ]; then
                    echo "ERROR: Failed to authenticate with Vault"
                    echo "Please ensure Kubernetes auth is configured with a 'backup' role"
                    exit 1
                  fi
                  export VAULT_TOKEN
                  {{- end }}
                  
                  # Create snapshot
                  TIMESTAMP=$(date +%Y%m%d-%H%M%S)
                  SNAPSHOT_FILE="/snapshots/vault-${TIMESTAMP}.snap"
                  
                  echo "Creating Raft snapshot..."
                  if vault operator raft snapshot save "$SNAPSHOT_FILE"; then
                    echo "Snapshot created successfully"
                    ls -lh "$SNAPSHOT_FILE"
                    # Write timestamp for rclone container
                    echo "$TIMESTAMP" > /snapshots/timestamp
                  else
                    echo "ERROR: Failed to create snapshot"
                    exit 1
                  fi
              volumeMounts:
                - name: snapshots
                  mountPath: /snapshots
                {{- if .Values.backup.vaultTokenSecretName }}
                - name: vault-token
                  mountPath: /vault/token
                  readOnly: true
                {{- end }}
              resources:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 256Mi
                  cpu: 200m
          
          ## Main Container: Upload to S3 using rclone
          containers:
            - name: upload
              image: {{ .Values.backup.rclone.image.repository }}:{{ .Values.backup.rclone.image.tag }}
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -ec
                - |
                  set -e
                  echo "=== Rclone Upload Started ==="
                  echo "Cluster: {{ .Values.backup.clusterName | default (include "common.names.fullname" .) }}"
                  
                  # Read timestamp
                  TIMESTAMP=$(cat /snapshots/timestamp)
                  SNAPSHOT_FILE="/snapshots/vault-${TIMESTAMP}.snap"
                  REMOTE_PATH="{{ include "vault.backup.remotePath" . }}"
                  
                  echo "Remote path: $REMOTE_PATH"
                  
                  if [ ! -f "$SNAPSHOT_FILE" ]; then
                    echo "ERROR: Snapshot file not found: $SNAPSHOT_FILE"
                    exit 1
                  fi
                  
                  echo "Snapshot file: $SNAPSHOT_FILE"
                  ls -lh "$SNAPSHOT_FILE"
                  
                  # Upload timestamped snapshot
                  echo "Uploading to ${REMOTE_PATH}/vault-${TIMESTAMP}.snap ..."
                  rclone copy "$SNAPSHOT_FILE" "${REMOTE_PATH}/" \
                    --config /config/rclone.conf \
                    --progress \
                    --transfers {{ .Values.backup.rclone.transfers | default 4 }} \
                    --checkers {{ .Values.backup.rclone.checkers | default 8 }} \
                    --retries {{ .Values.backup.rclone.retries | default 3 }} \
                    --retries-sleep 10s \
                    --low-level-retries 10 \
                    --stats 30s \
                    --stats-one-line \
                    -v
                  
                  # Copy as latest.snap (for restore)
                  echo "Copying to ${REMOTE_PATH}/latest.snap ..."
                  rclone copyto "$SNAPSHOT_FILE" "${REMOTE_PATH}/latest.snap" \
                    --config /config/rclone.conf \
                    --progress \
                    -v
                  
                  echo "Upload completed successfully"
                  
                  # Clean up old snapshots
                  RETENTION_DAYS={{ .Values.backup.retentionDays | default 7 }}
                  echo "Cleaning up snapshots older than $RETENTION_DAYS days..."
                  
                  rclone delete "${REMOTE_PATH}/" \
                    --config /config/rclone.conf \
                    --min-age "${RETENTION_DAYS}d" \
                    --include "vault-*.snap" \
                    -v
                  
                  # List remaining snapshots
                  echo "Remaining snapshots:"
                  rclone lsf "${REMOTE_PATH}/" --config /config/rclone.conf | grep "^vault-" | sort -r | head -10
                  
                  # Verify upload
                  echo "Verifying latest.snap..."
                  rclone ls "${REMOTE_PATH}/latest.snap" --config /config/rclone.conf
                  
                  echo "=== Backup completed successfully ==="
              env:
                {{- if .Values.backup.rclone.credentialsSecretName }}
                - name: RCLONE_CONFIG_S3_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backup.rclone.credentialsSecretName }}
                      key: {{ .Values.backup.rclone.accessKeySecretKey | default "AWS_ACCESS_KEY_ID" }}
                - name: RCLONE_CONFIG_S3_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.backup.rclone.credentialsSecretName }}
                      key: {{ .Values.backup.rclone.secretKeySecretKey | default "AWS_SECRET_ACCESS_KEY" }}
                {{- end }}
              volumeMounts:
                - name: snapshots
                  mountPath: /snapshots
                - name: rclone-config
                  mountPath: /config
                  readOnly: true
              {{- with .Values.backup.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          
          volumes:
            - name: snapshots
              emptyDir:
                {{- if .Values.backup.snapshot.useMemory }}
                medium: Memory
                {{- end }}
                sizeLimit: {{ .Values.backup.snapshot.sizeLimit | default "2Gi" }}
            - name: rclone-config
              configMap:
                name: {{ include "common.names.fullname" . }}-rclone-config
            {{- if .Values.backup.vaultTokenSecretName }}
            - name: vault-token
              secret:
                secretName: {{ .Values.backup.vaultTokenSecretName }}
            {{- end }}
{{- end }}
