{{- if and .Values.server.enabled .Values.backup.enabled }}
## Configure Vault Kubernetes auth for backup:
## vault write auth/kubernetes/role/backup \
##   bound_service_account_names={{ include "common.names.fullname" . }}-backup \
##   bound_service_account_namespaces={{ .Release.Namespace }} \
##   policies=backup \
##   ttl=1h
##
## vault policy write backup - <<EOF
## path "sys/storage/raft/snapshot" {
##   capabilities = ["read"]
## }
## EOF

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.names.fullname" . }}-backup
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: backup
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}-backup
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "common.names.fullname" . }}-backup
subjects:
  - kind: ServiceAccount
    name: {{ include "common.names.fullname" . }}-backup
    namespace: {{ include "common.names.namespace" . | quote }}
{{- end }}
