{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if not .Values.existingRecordsConfigmap }}
{{- $records := .Values.recordsConfig | deepCopy }}
{{- if .Values.clusterMode.enabled }}
{{- $override := dict "records" (dict "url_remap" (dict "strategies" (dict "filename" "/tmp/strategies-rendered.yaml"))) }}
{{- $records = mergeOverwrite $records $override }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-records" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  records.yaml: |
    {{- $records | toYaml | nindent 4 }}
{{- end }}
